create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  user_id uuid not null,
  phone_number text not null,
  amount integer not null check (amount > 0),
  merchant_request_id text,
  checkout_request_id text unique,
  response_code text,
  response_description text,
  customer_message text,
  mpesa_receipt_number text,
  transaction_date text,
  result_code integer,
  result_desc text,
  status text not null default 'initiated',
  raw_request jsonb,
  raw_response jsonb,
  callback_payload jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists payments_order_id_idx on public.payments(order_id);
create index if not exists payments_user_id_idx on public.payments(user_id);
create unique index if not exists payments_paid_order_unique_idx
on public.payments(order_id)
where status = 'paid';

create table if not exists public.payment_logs (
  id bigint generated by default as identity primary key,
  payment_id bigint references public.payments(id) on delete cascade,
  order_id bigint not null references public.orders(id) on delete cascade,
  event_type text not null,
  event_payload jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists payment_logs_order_id_idx on public.payment_logs(order_id);

create or replace function public.reduce_stock(product_id bigint, qty integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if qty <= 0 then
    raise exception 'Quantity to reduce must be greater than zero';
  end if;

  update public.products
  set stock_quantity = stock_quantity - qty
  where id = product_id
    and stock_quantity >= qty;

  if not found then
    raise exception 'Insufficient stock or product not found for product %', product_id;
  end if;
end;
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists payments_set_updated_at on public.payments;
create trigger payments_set_updated_at
before update on public.payments
for each row
execute procedure public.set_updated_at();

alter table public.payments enable row level security;
alter table public.payment_logs enable row level security;

drop policy if exists "Users can view own payments" on public.payments;
create policy "Users can view own payments"
on public.payments
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can view own payment logs" on public.payment_logs;
create policy "Users can view own payment logs"
on public.payment_logs
for select
to authenticated
using (
  exists (
    select 1
    from public.payments
    where public.payments.id = payment_logs.payment_id
      and public.payments.user_id = auth.uid()
  )
);

drop policy if exists "Service role manages payments" on public.payments;
create policy "Service role manages payments"
on public.payments
for all
to service_role
using (true)
with check (true);

drop policy if exists "Service role manages payment logs" on public.payment_logs;
create policy "Service role manages payment logs"
on public.payment_logs
for all
to service_role
using (true)
with check (true);
