-- Run this in the Supabase SQL Editor.
-- Creates a wishlist table and secure CRUD policies for each signed-in user.

create table if not exists public.wishlist (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  added_at timestamptz not null default now(),
  unique (user_id, product_id)
);

alter table public.wishlist enable row level security;

drop policy if exists "Users can view own wishlist" on public.wishlist;
create policy "Users can view own wishlist"
on public.wishlist
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own wishlist" on public.wishlist;
create policy "Users can insert own wishlist"
on public.wishlist
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own wishlist" on public.wishlist;
create policy "Users can delete own wishlist"
on public.wishlist
for delete
to authenticated
using (auth.uid() = user_id);

create index if not exists wishlist_user_id_idx on public.wishlist(user_id);
create index if not exists wishlist_product_id_idx on public.wishlist(product_id);
